const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),course=JSON.parse(fs.readFileSync(path.join(root,'course.json'),'utf8'));
(async()=>{let server,browser;try{
server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname,file=path.resolve(root,'.'+(p==='/'?'/index.html':p));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(e,data)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let args=[];if(process.env.CHROMIUM_BUNDLE)args=(await import(process.env.CHROMIUM_BUNDLE)).default.args;
browser=await chromium.launch({headless:true,args,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});
const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForSelector('#lms-heading');
for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No overflow at '+width);const toggle=page.locator('[data-lms="outline"]');const initial=await toggle.getAttribute('aria-expanded');await toggle.click();assert.notEqual(await toggle.getAttribute('aria-expanded'),initial);await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),initial);}
await page.setViewportSize({width:390,height:844});const menu=page.locator('.lms-menu-button');await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');await page.getByRole('link',{name:'Reporting',exact:true}).click();assert.ok((await page.locator('#lms-main').innerText()).includes('Skills'));await page.locator('.lms-menu-button').click();await page.getByRole('link',{name:'Course',exact:true}).click();await page.locator('.lms-menu-button').click();await page.keyboard.press('Escape');assert.equal(await page.locator('.lms-menu-button').getAttribute('aria-expanded'),'false');
await page.setViewportSize({width:1440,height:900});if(await page.locator('[data-lms="outline"]').getAttribute('aria-expanded')==='false')await page.locator('[data-lms="outline"]').click();
await page.locator('[data-id="jsonorg-format"]').click();await page.locator('[data-lms="slide-next"]').click();assert.ok(await page.locator('.lms-prose pre code').count());
const rendered=await page.evaluate(()=>{const c=JSON.parse(document.querySelector('#lms-course-data').textContent);let count=0;function walk(ns){for(const n of ns){if(n.type==='section')walk(n.children);if(n.type==='slides')for(const s of n.slides){const el=document.createElement('div');el.innerHTML=LMSMarkdown(s.body);if(!el.textContent.trim())throw Error('Empty '+s.id);if(el.querySelector('script,iframe,[onerror],a[href^="javascript:"]'))throw Error('Unsafe '+s.id);count++;}}}walk(c.sections);return count;});assert.equal(rendered,195);
const safety=await page.evaluate(()=>{const el=document.createElement('div');el.innerHTML=LMSMarkdown('[unsafe](javascript:alert(1))\n\n<img src=x onerror=alert(1)>\n\n```html\n<script>alert(2)</script>\n```');return {unsafe:!!el.querySelector('script,img,[onerror],a[href^="javascript:"]'),code:el.querySelector('code').textContent};});assert.equal(safety.unsafe,false);assert.ok(safety.code.includes('<script>'));
await page.locator('[data-id="start"]').click();assert.equal(await page.locator('[data-lms="complete"]').isDisabled(),true);for(let i=1;i<course.sections[0].children[0].slides.length;i++)await page.locator('[data-lms="slide-next"]').click();await page.locator('[data-lms-notes="start"]').fill('My JSON study note');await page.locator('[data-lms-notes="start"]').dispatchEvent('input');await page.locator('[data-lms="complete"]').click();await page.reload();assert.ok((await page.locator('[data-id="start"]').innerText()).includes('Complete'));assert.equal(await page.locator('[data-lms-notes="start"]').inputValue(),'My JSON study note');
const quiz=course.sections[1].children.at(-1);await page.locator('[data-id="'+quiz.id+'"]').click();for(const q of quiz.questions)await page.locator(`input[name="q-${q.id}"][value="${q.answer}"]`).check();await page.locator('#lms-quiz button[type="submit"]').click();assert.ok((await page.locator('.lms-result').first().innerText()).includes('100%'));
await page.locator('.lms-header-actions [data-view="report"]').click();assert.ok((await page.locator('#lms-main').innerText()).includes('JSON syntax'));
await page.locator('.lms-header-actions [data-view="settings"]').click();await page.locator('#lms-unlock-all').uncheck();await page.locator('.lms-header-actions [data-view="learn"]').click();assert.equal(await page.locator('[data-id="json-final"]').isDisabled(),true);
const copy=page.getByRole('button',{name:'Copy entire course text'});await page.evaluate(()=>document.querySelectorAll('details[data-lms-section]').forEach(el=>el.open=false));await copy.click();await page.waitForFunction(()=>document.querySelector('.lms-copy-status').textContent.startsWith('Entire course copied'));const text=await page.evaluate(()=>navigator.clipboard.readText());
const copied=await page.evaluate(text=>{const c=JSON.parse(document.querySelector('#lms-course-data').textContent),missing=[];function walk(ns){for(const n of ns){if(!text.includes(n.title))missing.push(n.id);if(n.type==='section')walk(n.children);if(n.type==='slides')for(const s of n.slides){if(!text.includes(s.title))missing.push(s.id);const el=document.createElement('div');el.innerHTML=LMSMarkdown(s.body);for(const code of el.querySelectorAll('pre'))if(!text.includes(code.textContent))missing.push(s.id+':code');}if(n.type==='quiz')for(const q of n.questions){if(!text.includes(q.prompt)||!text.includes(q.explanation)||!text.includes('Correct answer: '+(q.answer+1)+'. '+q.options[q.answer]))missing.push(q.id);}}}walk(c.sections);walk([c.finalQuiz]);return missing;},text);assert.deepEqual(copied,[]);assert.ok(!text.includes('My JSON study note'));assert.ok(text.includes('https://www.json.org/json-en.html'));
await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('Denied');}}}));await copy.click();await page.waitForSelector('.lms-copy-fallback textarea');assert.equal(await page.locator('.lms-copy-fallback textarea').inputValue(),text);
await page.locator('.lms-home').click();
await page.evaluate(()=>document.querySelectorAll('details[data-lms-section]').forEach(el=>el.open=true));await page.locator('[data-id="jsonorg-format"]').click();await page.locator('[data-lms="slide-next"]').click();await page.screenshot({path:path.join(process.env.LMS_TEST_ARTIFACTS||require('node:os').tmpdir(),'json-lms-desktop.png')});
await page.setViewportSize({width:390,height:844});await page.locator('.lms-menu-button').click();await page.waitForFunction(()=>{const r=document.querySelector('#lms-nav').getBoundingClientRect();return Math.abs(r.right-innerWidth)<1 && r.left>=0;});await page.screenshot({path:path.join(process.env.LMS_TEST_ARTIFACTS||require('node:os').tmpdir(),'json-lms-mobile.png')});
assert.deepEqual(errors,[]);console.log('PASS: 390/768/1440 layouts, mobile menu, all 195 slides, safe Markdown, completion/notes persistence, grading, reports, final gates, full clipboard copy and fallback');
}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
